name: "test"

on: 
  [push]

jobs:
  Test:
    runs-on: ubuntu-24.04
    steps:
      - name: "test"
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            whoami
            cd ~
            la 
            echo "Successfully executed commands"
